[package]
authors = ["github.scott@gmail.com"]
edition = "2021"
name = "rbasefind"
version = "0.2.0"

[dependencies]
byteorder = "1.4.3"
clap = "4"
fnv = "1.0.7"
num_cpus = "1.15.0"
pbr = "1.0.4"
regex = "1.7.1"
