[package]
name = "rbasefind"
version = "0.1.2"
authors = ["github.scott@gmail.com"]

[dependencies]
byteorder = "1.3.2"
clap = "2.33.0"
fnv = "1.0.6"
num_cpus = "1.10.1"
regex = "1.3.1"
pbr = "1.0.2"
ocl = "0.19.3"
