[package]
name = "rbasefind"
version = "0.1.2"
authors = ["github.scott@gmail.com"]
edition = "2024"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.23", features = ["derive"] }
fnv = "1.0.7"
num_cpus = "1.16.0"
regex = "1.11.1"
pbr = "1.1.1"
ocl = "0.19.7"
