[package]
authors = ["github.scott@gmail.com"]
edition = "2021"
name = "rbasefind"
version = "0.1.3"

[dependencies]
byteorder = "1.4.3"
clap = "3"
fnv = "1.0.7"
num_cpus = "1.15.0"
pbr = "1.1.1"
regex = "1.8.4"
